### ISSUE TITLE
bug: Missing informations for development on README 

### ISSUE THREAD

**Issue by mogui** [webcatalog/webcatalog-legacy#1199]
# Bug Report
**Specifications:**
- App Version: master branch
- OS: macOS

**Description:**
Try to run the development commands explained on the readme, but:
1. the yarn command  `template:install` does not exists
2. when I try to run `yarn electron-dev` application doesn't start correctly since it misses some environment variables.

It seems some info on how to correctly  start development are missing

**Steps to Reproduce:**
```
 git clone git@github.com:sourcesense/webcatalog-app.git
cd webcatalog-app     
yarn template:install   
```

**Comment by quanglam2807** [comment]
Thanks for bringing this up. I've updated the documentation. You can now run the code locally.

**Comment by mogui** [comment]
thanks @quanglam2807 , regarding the template app instead, it is the webcatalog engine right?
it seems documentation  isn't correct there too

**Comment by mogui** [comment]
sorry again @quanglam2807 still problems the engine doesn't starts correctly even with the correct env vars:

```
Starting the development server...
[0] 
[0] (node:78678) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time
[0] Compiled successfully!
[0] 
[0] You can now view Singlebox in the browser.
[0] 
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://192.168.1.209:3000
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use yarn build.
[0] 
[1] (node:78726) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1] wait-on http://localhost:3000 && electron . exited with code 0
--> Sending SIGTERM to other processes..
[0] cross-env BROWSER=none yarn start exited with code 1
verbose 13.83342162 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:790:113)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:34550:30
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by quanglam2807** [comment]
@mogui I don't know what happened.

Can you change this line in `package.json`
```
 "electron-dev": "concurrently \"cross-env BROWSER=none yarn start\" \"wait-on http://localhost:3000 && electron .\" -k",
```
to 
```
 "electron-dev": "concurrently \"cross-env BROWSER=none yarn start\" \"wait-on http://localhost:3000 && electron .\"",
```
(removing `-k)

and try again, please?

**Comment by mogui** [comment]
same result, but now it remains hanged up 
```
concurrently "cross-env BROWSER=none yarn start" "wait-on http://localhost:3000 && electron ."
$ react-scripts start
[0] ℹ ｢wds｣: Project is running at http://192.168.1.209/
[0] ℹ ｢wds｣: webpack output is served from 
[0] ℹ ｢wds｣: Content not from webpack is served from /Users/sourcenik/projects/webcatalog-engine/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0] 
[0] (node:6478) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time
[0] Compiled successfully!
[0] 
[0] You can now view Singlebox in the browser.
[0] 
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://192.168.1.209:3000
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use yarn build.
[0] 
[1] (node:6516) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1] wait-on http://localhost:3000 && electron . exited with code 0

```

**Comment by quanglam2807** [comment]
So strange. The app has a mechanism of detecting another running instance and if it finds one, it will automatically quit. I suspect that there might be another instance hanging somewhere causing this mechanism to trigger.

https://github.com/webcatalog/webcatalog-engine/blob/master/public/electron.js#L51

Maybe, you can try to restart the app or remove these lines of code? And then try again.

**Comment by mogui** [comment]
oh I see, I was indeed having anther running instance, sorry now it works!  sorry to bother so much  
thank you
