### ISSUE TITLE
Launching the app fails on Linux

### ISSUE THREAD

**Issue by federicosnobohm** [webcatalog/webcatalog-legacy#71]
not working manjaro

**Comment by quanglam2807** [comment]
Kevin Baer to me
```
Error I get when executing appimage using linux mint

module.js:545
     throw err;
     ^

Error: Cannot find module 
'/tmp/.mount_webcatvzRv8K/resources/electron.asar/browser/init.js'
     at Function.Module._resolveFilename (module.js:543:15)
     at Function.Module._load (module.js:473:25)
     at Function.Module.runMain (module.js:683:10)
     at startup (bootstrap_node.js:196:16)
     at bootstrap_node.js:622:3
```

**Comment by quanglam2807** [comment]
Related to electron-userland/electron-builder#2958
