### ISSUE TITLE
bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#721]
# Bug Report
**Current Behaviour:**
Happened on launch after a reboot.

**Expected Behavior:**
Should just launch without error

**Steps to Reproduce:**
Not sure but it did happen with multiple apps.

**Additional Context**
```
Uncaught Exception:
Error: The 'screen' module can't be used before the app 'ready' event
    at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6962:30)
    at ensureWindowVisibleOnSomeDisplay (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:58:28)
    at validateState (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:77:7)
    at module.exports (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:165:3)
    at Object.createAsync (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/build/windows/main.js:112:27)
    at commonInit (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/build/electron.js:88:16)
    at App.<anonymous> (/Applications/WebCatalog Apps/LastPass.app/Contents/Resources/app.asar/build/electron.js:196:7)
    at App.emit (events.js:210:5)
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/6428977/79449723-a7eb4300-7fdb-11ea-85e0-e837a1c352be.png">

**Comment by quanglam2807** [comment]
@surferking Thanks for reporting! I couldn't reproduce the bug but I think I know what causes it. A fix will be available soon.

**Comment by marcusquinn** [comment]
Just got it again after a restart:

```
Uncaught Exception:
Error: The 'screen' module can't be used before the app 'ready' event
    at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6962:30)
    at ensureWindowVisibleOnSomeDisplay (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:58:28)
    at validateState (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:77:7)
    at module.exports (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:165:3)
    at createAsync (/Applications/WebCatalog.app/Contents/Resources/app/build/windows/main.js:147:27)
    at Object.show (/Applications/WebCatalog.app/Contents/Resources/app/build/windows/main.js:191:5)
    at App.<anonymous> (/Applications/WebCatalog.app/Contents/Resources/app/build/electron.js:83:16)
    at App.emit (events.js:210:5)
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/6428977/79581865-ed367000-80c2-11ea-9bf5-3b78eb573b3e.png">

**Comment by quanglam2807** [comment]
@surferking Thank you for the screenshot! This bug is really strange. I can't reproduce it on my Mac at all. Do you mean full computer restart or just app restart?

**Comment by marcusquinn** [comment]
> @surferking Thank you for the screenshot! This bug is really strange. I can't reproduce it on my Mac at all. Do you mean full computer restart or just app restart?

Full Mac restart. I know what intermittent issues are like to resolve, so let's just keep the ticket for history purposes but I wouldn't spend time on it if you can't reproduce. I'll just watch for any other cause *if* it happens again.

**Comment by quanglam2807** [comment]
> Just got it again after a restart:
> 
> ```
> Uncaught Exception:
> Error: The 'screen' module can't be used before the app 'ready' event
>     at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6962:30)
>     at ensureWindowVisibleOnSomeDisplay (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:58:28)
>     at validateState (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:77:7)
>     at module.exports (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/electron-window-state/index.js:165:3)
>     at createAsync (/Applications/WebCatalog.app/Contents/Resources/app/build/windows/main.js:147:27)
>     at Object.show (/Applications/WebCatalog.app/Contents/Resources/app/build/windows/main.js:191:5)
>     at App.<anonymous> (/Applications/WebCatalog.app/Contents/Resources/app/build/electron.js:83:16)
>     at App.emit (events.js:210:5)
> ```
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/6428977/79581865-ed367000-80c2-11ea-9bf5-3b78eb573b3e.png">

I just realize this is different from the one described initially as it occurs in WebCatalog.app, not in generate apps.
